enum FacebookCapFlags {
    FB_CP_ACKNOWLEDGED_DELIVERY = 1 << 0,
    FB_CP_PROCESSING_LASTACTIVE_PRESENCEINFO = 1 << 1,
    FB_CP_EXACT_KEEPALIVE = 1 << 2,
    FB_CP_REQUIRES_JSON_UNICODE_ESCAPES = 1 << 3,
    FB_CP_DELTA_SENT_MESSAGE_ENABLED = 1 << 4,
    FB_CP_USE_ENUM_TOPIC = 1 << 5,
    FB_CP_SUPPRESS_GETDIFF_IN_CONNECT = 1 << 6,
    FB_CP_USE_THRIFT_FOR_INBOX = 1 << 7,
    FB_CP_USE_SEND_PINGRESP = 1 << 8,
    FB_CP_REQUIRE_REPLAY_PROTECTION = 1 << 9,
    FB_CP_DATA_SAVING_MODE = 1 << 10,
    FB_CP_TYPING_OFF_WHEN_SENDING_MESSAGE = 1 << 11,
    FB_CP_PERMISSION_USER_AUTH_CODE = 1 << 12,
    FB_CP_FBNS_EXPLICIT_DELIVERY_ACK = 1 << 13,
    FB_CP_LARGE_PAYLOAD_SUPPORTED = 1 << 14
}

export default FacebookCapFlags
